# Generated by Django 4.1.7 on 2024-05-17 07:37

import app.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_status_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updation',
            field=app.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
